name:                conway
version:             0.1.0.0
github:              "https://github.com/timmyw/conway#readme"
license:             BSD3
author:              "Tim Whelan"
maintainer:          "tim@zipt.co"
copyright:           "2019 Tim Whelan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timmyw/conway#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Conway.Board
    - Conway.BoardDisplay
  dependencies:
    - random
    - aeson
    - bytestring
    
executables:
  conway:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conway
    - text
    - cmdargs
    - ansi-terminal
    - unix
    - time
    - old-locale

tests:
  conway-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conway
